"""Step 3b: Hyperparameter tuning with Optuna.

Runs cross-validated Optuna search on the train split (60%) only, then reports
AUC on val (20%) with the best params. Test set (20%) is never loaded here.

Loads member_split.json from the source tag's features dir to guarantee the same
train/val/test split is used across all experiments.

Usage:
    pipenv run python3 scripts/3b_tune_hyperparams.py --tag v1
    pipenv run python3 scripts/3b_tune_hyperparams.py --tag v1 --n-trials 50 --cv-folds 3
    pipenv run python3 scripts/3b_tune_hyperparams.py --tag v1_rfe --source-tag v1 --feature-list output/features/v1_rfe/selected_features_rfe.txt
"""

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import optuna
from sklearn.model_selection import StratifiedKFold, cross_val_score
from xgboost import XGBClassifier

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import pyarrow as pa
import pyarrow.parquet as pq

from xgboost_model import config
from xgboost_model.data import prep_features
from xgboost_model.training import load_split_ids

optuna.logging.set_verbosity(optuna.logging.WARNING)


def objective(trial, X, y, cv_folds: int, random_state: int, device: str, spw):
    params = {
        "objective": "binary:logistic",
        "eval_metric": "auc",
        "tree_method": "hist",
        "device": device,
        "n_estimators": 300,
        "max_depth": trial.suggest_int("max_depth", 3, 7),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.3, 0.8),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 5.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.0, 5.0),
        "random_state": random_state,
        "n_jobs": -1,
        "verbosity": 0,
    }
    if spw is not None:
        params["scale_pos_weight"] = spw

    model = XGBClassifier(**params)
    cv = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=random_state)
    scores = cross_val_score(model, X, y, cv=cv, scoring="roc_auc", n_jobs=1)
    return float(scores.mean())


def main():
    parser = argparse.ArgumentParser(description="Optuna HPO on selected features")
    parser.add_argument("--tag", required=True, help="Run tag (output goes here)")
    parser.add_argument("--source-tag", default=None,
                        help="Read parquet and split from this tag's data dir (default: same as --tag)")
    parser.add_argument("--feature-list", default=None,
                        help="Path to feature list file (default: selected_features_top<N>.txt)")
    parser.add_argument("--n-trials", type=int, default=None)
    parser.add_argument("--cv-folds", type=int, default=None)
    parser.add_argument("--timeout", type=int, default=None, help="Timeout in seconds")
    args = parser.parse_args()

    n_trials = args.n_trials or config.HPO_N_TRIALS
    cv_folds = args.cv_folds or config.HPO_CV_FOLDS
    timeout = args.timeout or config.HPO_TIMEOUT
    data_tag = args.source_tag or args.tag

    print(f"Step 3b: Hyperparameter tuning (tag={args.tag}, trials={n_trials}, cv={cv_folds})")
    print(f"  data_tag={data_tag}  CV on train split only — val used only for sanity check")

    parquet_path = config.DATA_DIR / data_tag / "features.parquet"
    if not parquet_path.exists():
        print(f"  ERROR: {parquet_path} not found — run step 1 first")
        sys.exit(1)

    # Load split IDs (generated by step 3) — same split across all experiments
    split_path = config.FEATURES_DIR / data_tag / "member_split.json"
    if not split_path.exists():
        print(f"  ERROR: {split_path} not found — run step 3 first")
        sys.exit(1)
    split_ids = load_split_ids(split_path)
    train_id_set = set(split_ids["train"])
    val_id_set = set(split_ids["val"])
    print(f"  Split: train={len(train_id_set):,}  val={len(val_id_set):,}  "
          f"test={len(split_ids['test']):,} (test not loaded)")

    # Load feature list BEFORE opening parquet so we can do selective column reads
    if args.feature_list:
        feat_path = Path(args.feature_list)
    else:
        feat_path = config.FEATURES_DIR / data_tag / f"selected_features_top{config.TOP_N}.txt"
    if not feat_path.exists():
        print(f"  ERROR: {feat_path} not found — run step 3 (or 3c) first")
        sys.exit(1)
    with open(feat_path) as f:
        selected = [line.strip() for line in f if line.strip()]
    print(f"  Loaded {len(selected)} selected features from {feat_path.name}")

    # Read only the needed columns to avoid loading the full wide table into memory
    cols_to_load = selected + [config.OUTCOME_COLUMN, config.ID_COLUMN, config.INDEX_DATE_COLUMN]
    table = pq.read_table(parquet_path, columns=cols_to_load)
    for i in range(len(table.schema)):
        col = table.column(i)
        if pa.types.is_date(col.type) or pa.types.is_time(col.type):
            table = table.set_column(i, table.schema.field(i).name, col.cast(pa.string()))
    df = table.to_pandas()
    print(f"  Loaded {len(df):,} rows x {len(df.columns)} cols")

    # Filter to train split only — never touch test, never touch val during HPO
    df_train = df[df[config.ID_COLUMN].isin(train_id_set)].reset_index(drop=True)
    df_val = df[df[config.ID_COLUMN].isin(val_id_set)].reset_index(drop=True)
    print(f"  Train rows: {len(df_train):,}  Val rows: {len(df_val):,}")

    X_train, y_train, _ = prep_features(df_train, config.NON_FEATURE_COLUMNS,
                                        config.EXCLUDE_PATTERNS, config.OUTCOME_COLUMN)
    available = [c for c in selected if c in X_train.columns]
    X_train = X_train[available]
    print(f"  Using {len(available)} features | positives: {y_train.sum():,} / {len(y_train):,} ({y_train.mean():.2%})")

    # Auto scale_pos_weight from train split
    spw = config.SCALE_POS_WEIGHT
    if spw is None:
        neg = (y_train == 0).sum()
        pos = (y_train == 1).sum()
        spw = float(neg) / float(pos) if pos > 0 else 1.0
        print(f"  Auto scale_pos_weight: {spw:.1f}")

    # Run Optuna — cross-val within train (60%) only
    print(f"  Starting Optuna search (timeout={timeout}s) ...")
    t0 = time.time()

    study = optuna.create_study(
        direction="maximize",
        sampler=optuna.samplers.TPESampler(seed=config.RANDOM_STATE),
    )
    study.optimize(
        lambda trial: objective(trial, X_train.values, y_train.values, cv_folds,
                                config.RANDOM_STATE, config.DEVICE, spw),
        n_trials=n_trials,
        timeout=timeout,
        show_progress_bar=True,
    )

    elapsed = time.time() - t0
    print(f"\n  Completed {len(study.trials)} trials in {elapsed:.0f}s")
    print(f"  Best AUC (CV on train): {study.best_value:.4f}")
    print(f"  Best params:            {study.best_params}")

    # Val sanity check with best params
    X_val, y_val, _ = prep_features(df_val, config.NON_FEATURE_COLUMNS,
                                    config.EXCLUDE_PATTERNS, config.OUTCOME_COLUMN)
    available_val = [c for c in selected if c in X_val.columns]
    X_val_sel = X_val[available_val]
    best_params = {
        "objective": "binary:logistic",
        "eval_metric": "auc",
        "tree_method": "hist",
        "device": config.DEVICE,
        "n_estimators": 300,
        **study.best_params,
        "scale_pos_weight": spw,
        "random_state": config.RANDOM_STATE,
        "verbosity": 0,
    }
    val_model = XGBClassifier(**best_params)
    val_model.fit(X_train.values, y_train.values)
    val_preds = val_model.predict_proba(X_val_sel.values)[:, 1]
    from sklearn.metrics import roc_auc_score
    val_auc = roc_auc_score(y_val.values, val_preds)
    print(f"  Val AUC (sanity check): {val_auc:.4f}")

    # Save best params (n_estimators intentionally excluded — step 4 uses config value)
    out_path = config.tag_path(config.FEATURES_DIR, args.tag, "best_params.json")
    with open(out_path, "w") as f:
        json.dump(study.best_params, f, indent=2)
    print(f"  Saved: {out_path}")

    # Save full study results for reference
    trials_df = study.trials_dataframe()
    trials_out = config.tag_path(config.FEATURES_DIR, args.tag, "hpo_trials.csv")
    trials_df.to_csv(trials_out, index=False)
    print(f"  Trials: {trials_out}")

    print(f"\nNext: pipenv run python3 scripts/4_train_model.py --tag {args.tag} --source-tag {data_tag}")


if __name__ == "__main__":
    main()
